name: pop
description: Popularity Contest

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0+2
  html: ^0.14.0+2
  trotter: ^1.0.2
  provider: ^3.0.0
  flutter_spinkit: ^3.1.0
  shared_preferences: ^0.5.3+1
  firebase_auth: ^0.11.1+6
  google_sign_in: ^4.0.2
  firebase_core: ^0.4.0+3
  cloud_firestore: ^0.12.3
  audioplayers: ^0.12.1
  flutter_facebook_login: ^2.0.1






dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: PaytoneOne
      fonts:
        - asset: fonts/PaytoneOne-Regular.ttf

  assets:
    - images/
    - assets/


